import { Inter } from "next/font/google";
import { GeistSans } from 'geist/font/sans';

import "./globals.css";
import Navbar from '../components/navbar'
import Footer from '../components/footer'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${GeistSans.className} ${inter.className}`}>
      <body className="flex flex-col min-h-screen justify-between">
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
